package test.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookid
     *
     * @mbg.generated
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.cnt
     *
     * @mbg.generated
     */
    private Integer cnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookid
     *
     * @return the value of book.bookid
     *
     * @mbg.generated
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookid
     *
     * @param bookid the value for book.bookid
     *
     * @mbg.generated
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.cnt
     *
     * @return the value of book.cnt
     *
     * @mbg.generated
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.cnt
     *
     * @param cnt the value for book.cnt
     *
     * @mbg.generated
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }
}